import type { EmployeeProfile } from '../lib/supabase';
import { formatDate, formatDateTime, getPriorityScore, type GaImportRow, type GaOrganization, type GaResearchProgress } from '../lib/ga-crm';
import { GradeBadge, ResearchBadge, StageBadge } from './GaCrmBadges';

interface Summary { readonly total: number; readonly phone: number; readonly uncontacted: number; readonly recentVerified: number; readonly regions: Readonly<Record<string, number>>; readonly grades: Readonly<Record<string, number>>; }

export function GaCrmPipelineView({ rows, onSelect }: { readonly rows: readonly GaOrganization[]; readonly onSelect: (row: GaOrganization) => void }) {
  const stages = ['미연락', '연락 예정', '담당자 연결', '교육 제안', '관심 있음', '일정 협의', '교육 확정'] as const;
  return <div className="grid gap-3 overflow-x-auto pb-2 xl:grid-cols-7">{stages.map((stage) => { const items = rows.filter((row) => row.sales_stage === stage); return <section key={stage} className="min-w-[220px] rounded-2xl bg-slate-100 p-3"><div className="flex items-center justify-between"><h3 className="text-sm font-bold text-slate-800">{stage}</h3><span className="rounded-full bg-white px-2 py-0.5 text-xs text-slate-500">{items.length}</span></div><div className="mt-3 space-y-2">{items.map((row) => <button type="button" key={row.id} onClick={() => onSelect(row)} className="w-full rounded-xl bg-white p-3 text-left shadow-sm ring-1 ring-slate-200 transition hover:-translate-y-0.5 hover:ring-brand-300"><div className="flex items-center justify-between gap-2"><span className="truncate text-sm font-semibold text-slate-800">{row.organization_name}</span><GradeBadge grade={row.reliability_grade} /></div><p className="mt-1 truncate text-xs text-slate-500">{row.ga_company_name} · {row.district}</p><p className="mt-2 text-xs font-semibold text-brand-700">우선순위 {getPriorityScore(row)}</p></button>)}{items.length === 0 && <p className="py-5 text-center text-xs text-slate-400">대상이 없습니다.</p>}</div></section>; })}</div>;
}

export function GaCrmEducationView({ rows, onSelect }: { readonly rows: readonly GaOrganization[]; readonly onSelect: (row: GaOrganization) => void }) {
  const scheduled = rows.filter((row) => row.education_scheduled_at || row.education_interest).sort((left, right) => (left.education_scheduled_at ?? '9999').localeCompare(right.education_scheduled_at ?? '9999'));
  return <section className="rounded-2xl bg-white p-5 shadow-card ring-1 ring-slate-100"><div className="flex items-center justify-between"><div><h2 className="text-lg font-bold text-slate-900">교육 일정</h2><p className="mt-1 text-sm text-slate-500">무료 실무교육 관심 조직과 예정된 교육을 관리합니다.</p></div><span className="text-sm text-slate-500">{scheduled.length}건</span></div><div className="mt-5 overflow-x-auto"><table className="min-w-[760px] w-full text-left text-sm"><thead className="border-b border-slate-200 text-xs text-slate-500"><tr><th className="px-2 py-3">조직</th><th className="px-2 py-3">관심도</th><th className="px-2 py-3">희망 주제</th><th className="px-2 py-3">예정일</th><th className="px-2 py-3">예상 참석</th><th className="px-2 py-3">영업단계</th></tr></thead><tbody className="divide-y divide-slate-100">{scheduled.map((row) => <tr key={row.id} className="cursor-pointer hover:bg-brand-50/50" onClick={() => onSelect(row)}><td className="px-2 py-3"><p className="font-semibold text-slate-800">{row.organization_name}</p><p className="text-xs text-slate-500">{row.region} {row.district}</p></td><td className="px-2 py-3">{row.interest_level}</td><td className="px-2 py-3">{row.education_topic ?? '미정'}</td><td className="px-2 py-3 text-xs text-slate-500">{formatDateTime(row.education_scheduled_at)}</td><td className="px-2 py-3">{row.expected_attendees === null ? '미정' : `${row.expected_attendees}명`}</td><td className="px-2 py-3"><StageBadge stage={row.sales_stage} /></td></tr>)}</tbody></table>{scheduled.length === 0 && <p className="py-10 text-center text-sm text-slate-500">교육 관심 또는 일정이 등록된 조직이 없습니다.</p>}</div></section>;
}

export function GaCrmStatsView({ summary }: { readonly summary: Summary }) {
  const stats = [['전체 조직', summary.total], ['전화번호 확보', summary.phone], ['미연락 대상', summary.uncontacted], ['90일 내 검증', summary.recentVerified]];
  return <div className="space-y-4"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{stats.map(([label, value]) => <div key={String(label)} className="rounded-2xl bg-white p-4 shadow-card ring-1 ring-slate-100"><p className="text-sm text-slate-500">{label}</p><p className="mt-2 text-3xl font-bold text-slate-900">{Number(value).toLocaleString('ko-KR')}</p></div>)}</div><div className="grid gap-4 lg:grid-cols-2"><section className="rounded-2xl bg-white p-5 ring-1 ring-slate-100"><h3 className="font-semibold text-slate-900">지역별 데이터</h3><div className="mt-4 space-y-3">{['서울', '경기', '인천'].map((region) => <div key={region}><div className="flex justify-between text-sm"><span>{region}</span><strong>{summary.regions[region] ?? 0}건</strong></div><div className="mt-1 h-2 rounded-full bg-slate-100"><div className="h-2 rounded-full bg-brand-500" style={{ width: `${summary.total ? Math.max(4, ((summary.regions[region] ?? 0) / summary.total) * 100) : 0}%` }} /></div></div>)}</div></section><section className="rounded-2xl bg-white p-5 ring-1 ring-slate-100"><h3 className="font-semibold text-slate-900">신뢰도 분포</h3><div className="mt-4 grid grid-cols-5 gap-2">{['A+', 'A', 'B', 'C', 'D'].map((grade) => <div key={grade} className="rounded-xl bg-slate-50 p-3 text-center"><GradeBadge grade={grade as 'A+' | 'A' | 'B' | 'C' | 'D'} /><strong className="mt-2 block text-lg text-slate-900">{summary.grades[grade] ?? 0}</strong><span className="text-xs text-slate-500">건</span></div>)}</div><p className="mt-4 text-xs text-slate-500">공식 출처 1개만 확인된 초기 적재 데이터는 B/C로 유지됩니다. 독립 출처 교차검증 후 승격하세요.</p></section></div></div>;
}

export function GaCrmResearchView({ rows }: { readonly rows: readonly GaResearchProgress[] }) {
  return <section className="rounded-2xl bg-white p-5 shadow-card ring-1 ring-slate-100"><div className="flex items-center justify-between"><div><h2 className="text-lg font-bold text-slate-900">데이터 조사현황</h2><p className="mt-1 text-sm text-slate-500">지역별 조사 진행과 추가조사 필요 구간을 관리합니다.</p></div><span className="text-sm text-slate-500">{rows.filter((row) => row.status === '교차검증 완료').length}/{rows.length} 완료</span></div><div className="mt-5 overflow-x-auto"><table className="min-w-[760px] w-full text-left text-sm"><thead className="border-b border-slate-200 text-xs text-slate-500"><tr><th className="px-2 py-3">지역</th><th className="px-2 py-3">상태</th><th className="px-2 py-3">조직 수</th><th className="px-2 py-3">검색어 수</th><th className="px-2 py-3">최근 조사</th><th className="px-2 py-3">메모</th></tr></thead><tbody className="divide-y divide-slate-100">{rows.map((row) => <tr key={row.id}><td className="px-2 py-3 font-semibold">{row.region} {row.district}</td><td className="px-2 py-3"><ResearchBadge status={row.status} /></td><td className="px-2 py-3">{row.organization_count}건</td><td className="px-2 py-3">{row.query_count}개</td><td className="px-2 py-3 text-xs text-slate-500">{formatDateTime(row.last_searched_at)}</td><td className="max-w-xs truncate px-2 py-3 text-xs text-slate-500">{row.notes ?? '-'}</td></tr>)}</tbody></table>{rows.length === 0 && <p className="py-10 text-center text-sm text-slate-500">조사현황 테이블이 아직 준비되지 않았습니다.</p>}</div></section>;
}

interface GaCrmDataViewProps { readonly isAdmin: boolean; readonly rows: readonly GaOrganization[]; readonly importRows: readonly GaImportRow[]; readonly onImport: (file: File) => Promise<void>; readonly onExport: () => void; readonly employees: readonly EmployeeProfile[]; }

export function GaCrmDataView({ isAdmin, rows, importRows, onImport, onExport }: GaCrmDataViewProps) {
  const validCount = importRows.filter((row) => row.errors.length === 0).length;
  return <div className="space-y-4"><section className="rounded-2xl bg-white p-5 shadow-card ring-1 ring-slate-100"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-lg font-bold text-slate-900">데이터 관리</h2><p className="mt-1 text-sm text-slate-500">CSV 업로드는 행별 검증 결과를 남기고 오류 행을 제외합니다.</p></div><button type="button" onClick={onExport} className="rounded-xl border border-slate-200 px-3 py-2 text-sm font-semibold text-slate-700">현재 결과 CSV</button></div>{isAdmin ? <label className="mt-5 flex cursor-pointer flex-col items-center justify-center rounded-2xl border border-dashed border-brand-300 bg-brand-50/50 px-5 py-8 text-center"><span className="text-sm font-semibold text-brand-700">CSV 파일 선택</span><span className="mt-1 text-xs text-slate-500">GA법인명, 조직명, 지역, 시군구를 포함하세요.</span><input className="sr-only" type="file" accept=".csv,text/csv" onChange={(event) => { const file = event.target.files?.[0]; if (file) void onImport(file); }} /></label> : <p className="mt-5 rounded-xl bg-slate-50 px-4 py-3 text-sm text-slate-600">CSV 등록과 출처 변경은 관리자 권한에서만 가능합니다.</p>}{importRows.length > 0 && <div className="mt-4"><p className="text-sm font-semibold text-slate-800">최근 업로드 검증 결과: {validCount}건 적재 가능 / {importRows.length - validCount}건 오류</p><div className="mt-2 max-h-64 overflow-y-auto rounded-xl border border-slate-200">{importRows.map((row) => <div key={row.rowNumber} className="flex gap-3 border-b border-slate-100 px-3 py-2 text-xs last:border-0"><span className="font-semibold text-slate-500">{row.rowNumber}행</span><span className={row.errors.length > 0 ? 'text-red-700' : 'text-emerald-700'}>{row.errors.length > 0 ? row.errors.join(', ') : '검증 통과'}</span></div>)}</div></div>}</section><section className="rounded-2xl bg-white p-5 ring-1 ring-slate-100"><h3 className="font-semibold text-slate-900">중복 후보</h3><p className="mt-2 text-sm text-slate-500">주소·전화·법인명 유사도를 기반으로 후보 테이블을 별도로 보존합니다. 병합은 관리자 검토 후 처리하도록 다음 단계에서 연결할 수 있습니다.</p><div className="mt-3 grid gap-3 sm:grid-cols-3"><div className="rounded-xl bg-slate-50 p-3"><span className="text-xs text-slate-500">현재 조직</span><strong className="mt-1 block text-xl">{rows.length}건</strong></div><div className="rounded-xl bg-slate-50 p-3"><span className="text-xs text-slate-500">전화 미확인</span><strong className="mt-1 block text-xl">{rows.filter((row) => !row.representative_phone).length}건</strong></div><div className="rounded-xl bg-slate-50 p-3"><span className="text-xs text-slate-500">재검증 필요</span><strong className="mt-1 block text-xl">{rows.filter((row) => row.needs_reverification).length}건</strong></div></div></section></div>;
}
